### ISSUE TITLE
1.12.2 version errer

### ISSUE THREAD

**Issue by sewoo12** [TheLimeGlass/Sky#6]
Why is this error occurring?

11:04:56 INFO]: [Sky] Enabling Sky v1.0.1a
[11:04:56 ERROR]: #!#!
[11:04:56 ERROR]: #!#! [Skript] Severe Error:
[11:04:56 ERROR]: #!#! Sky's class me.limeglass.sky.elements.askyblock.expressions.ExprIslandLocked generated an exception while loading
[11:04:56 ERROR]: #!#!
[11:04:56 ERROR]: #!#! Your server platform appears to be unsupported by Skript. It might not work reliably.
[11:04:56 ERROR]: #!#! You can report this at https://github.com/SkriptLang/Skript/issues. However, we may be unable to fix the issue.
[11:04:56 ERROR]: #!#! It is recommended that you switch to Paper or Spigot, should you encounter more problems.
[11:04:56 ERROR]: #!#!
[11:04:56 ERROR]: #!#! Stack trace:
[11:04:56 ERROR]: #!#! java.lang.IllegalArgumentException: returnType must be a normal type
[11:04:56 ERROR]: #!#!     at ch.njol.skript.Skript.registerExpression(Skript.java:1296)
[11:04:56 ERROR]: #!#!     at ch.njol.skript.expressions.base.PropertyExpression.register(PropertyExpression.java:52)
[11:04:56 ERROR]: #!#!     at me.limeglass.sky.elements.askyblock.expressions.ExprIslandLocked.<clinit>(ExprIslandLocked.java:24)
[11:04:56 ERROR]: #!#!     at java.base/java.lang.Class.forName0(Native Method)
[11:04:56 ERROR]: #!#!     at java.base/java.lang.Class.forName(Class.java:467)
[11:04:56 ERROR]: #!#!     at ch.njol.skript.SkriptAddon.loadClasses(SkriptAddon.java:107)
[11:04:56 ERROR]: #!#!     at me.limeglass.sky.Sky.onEnable(Sky.java:61)
[11:04:56 ERROR]: #!#!     at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[11:04:56 ERROR]: #!#!     at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316)
[11:04:56 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[11:04:56 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395)
[11:04:56 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344)
[11:04:56 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442)
[11:04:56 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403)
[11:04:56 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341)
[11:04:56 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:289)
[11:04:56 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616)
[11:04:56 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:833)
[11:04:56 ERROR]: #!#!
[11:04:56 ERROR]: #!#! Version Information:
[11:04:56 ERROR]: Error occurred while enabling Sky v1.0.1a (Is it up to date?)
java.lang.IllegalStateException: null
        at ch.njol.skript.Skript.getVersion(Skript.java:207) ~[?:?]
        at ch.njol.skript.Skript.exception(Skript.java:1657) ~[?:?]
        at ch.njol.skript.Skript.exception(Skript.java:1482) ~[?:?]
        at ch.njol.skript.SkriptAddon.loadClasses(SkriptAddon.java:111) ~[?:?]
        at me.limeglass.sky.Sky.onEnable(Sky.java:61) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.12.2.jar:git-Paper-1618]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) ~[patched_1.12.2.jar:git-Paper-1618]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[patched_1.12.2.jar:git-Paper-1618]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395) ~[patched_1.12.2.jar:git-Paper-1618]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:289) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) ~[patched_1.12.2.jar:git-Paper-1618]
        at java.lang.Thread.run(Thread.java:833) [?:?]
[11:04:56 INFO]: [Sky] Disabling Sky v1.0.1a

**Comment by TheLimeGlass** [comment]
Fixed in next version 1.0.3
