### ISSUE TITLE
Why does this error occur?

### ISSUE THREAD

**Issue by sewoo12** [TheLimeGlass/Sky#8]
version 1.12.2 plz help 
skript 2.6 beta-3

[19:01:11 INFO]: [Sky] Enabling Sky v1.0.2
[19:01:11 ERROR]: #!#!
[19:01:11 ERROR]: #!#! [Skript] Severe Error:
[19:01:11 ERROR]: #!#! Sky's class me.limeglass.sky.elements.askyblock.expressions.ExprIslandLocked generated an exception while loading
[19:01:11 ERROR]: #!#!
[19:01:11 ERROR]: #!#! Your server platform appears to be unsupported by Skript. It might not work reliably.
[19:01:11 ERROR]: #!#! You can report this at https://github.com/SkriptLang/Skript/issues. However, we may be unable to fix the issue.
[19:01:11 ERROR]: #!#! It is recommended that you switch to Paper or Spigot, should you encounter more problems.
[19:01:11 ERROR]: #!#!
[19:01:11 ERROR]: #!#! Stack trace:
[19:01:11 ERROR]: #!#! java.lang.IllegalArgumentException: returnType must be a normal type
[19:01:11 ERROR]: #!#!     at ch.njol.skript.Skript.registerExpression(Skript.java:1317)
[19:01:11 ERROR]: #!#!     at ch.njol.skript.expressions.base.PropertyExpression.register(PropertyExpression.java:52)
[19:01:11 ERROR]: #!#!     at me.limeglass.sky.elements.askyblock.expressions.ExprIslandLocked.<clinit>(ExprIslandLocked.java:24)
[19:01:11 ERROR]: #!#!     at java.base/java.lang.Class.forName0(Native Method)
[19:01:11 ERROR]: #!#!     at java.base/java.lang.Class.forName(Class.java:467)
[19:01:11 ERROR]: #!#!     at ch.njol.skript.SkriptAddon.loadClasses(SkriptAddon.java:107)
[19:01:11 ERROR]: #!#!     at me.limeglass.sky.Sky.onEnable(Sky.java:49)
[19:01:11 ERROR]: #!#!     at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[19:01:11 ERROR]: #!#!     at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316)
[19:01:11 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[19:01:11 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395)
[19:01:11 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344)
[19:01:11 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442)
[19:01:11 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403)
[19:01:11 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341)
[19:01:11 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:289)
[19:01:11 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616)
[19:01:11 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:833)
[19:01:11 ERROR]: #!#!
[19:01:11 ERROR]: #!#! Version Information:
[19:01:11 ERROR]: Error occurred while enabling Sky v1.0.2 (Is it up to date?)
java.lang.IllegalStateException: null
        at ch.njol.skript.Skript.getVersion(Skript.java:210) ~[?:?]
        at ch.njol.skript.Skript.exception(Skript.java:1678) ~[?:?]
        at ch.njol.skript.Skript.exception(Skript.java:1503) ~[?:?]
        at ch.njol.skript.SkriptAddon.loadClasses(SkriptAddon.java:111) ~[?:?]
        at me.limeglass.sky.Sky.onEnable(Sky.java:49) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.12.2.jar:git-Paper-1618]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) ~[patched_1.12.2.jar:git-Paper-1618]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[patched_1.12.2.jar:git-Paper-1618]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395) ~[patched_1.12.2.jar:git-Paper-1618]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:289) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) ~[patched_1.12.2.jar:git-Paper-1618]
        at java.lang.Thread.run(Thread.java:833) [?:?]
[19:01:11 INFO]: [Sky] Disabling Sky v1.0.2

**Comment by TheLimeGlass** [comment]
Duplicate https://github.com/TheLimeGlass/Sky/issues/6
